pack:
	@mkdir -p dist/rev-to-nim-or-not-to-nim && cp src/main.exe dist/rev-to-nim-or-not-to-nim
	@cd dist && zip -9 -r rev-to-nim-or-not-to-nim.zip rev-to-nim-or-not-to-nim
	@echo Challenge packed.

clean:
	@rm -rf dist/*